name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    environment: x
    runs-on: ubuntu-latest
    steps:
      - id: hint
        name: Print Status URLs
        run: |
          echo "API: ${{ github.api_url }}/${{ github.repository }}/commits/${{ github.sha }}/status"
          echo "Web: ${{ github.server_url }}/${{ github.repository }}/commits/${{ github.sha }}"
